language: c
compiler: clang
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - pkg-config
    - cmake
    - openssl
    - libc-ares-dev
    - libev-dev
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - libopencv-dev
services:
- rabbitmq
node_js:
- '4'
before_install:
- echo Jippi 
install:
- export CC=gcc-4.8
- export CXX=g++-4.8
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake -DWITH_SRV=off -DCMAKE_INSTALL_PREFIX=../build/install .
- make install
- cd -
- mkdir -p build/
- curl -sSL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar -xzC ./build
- export PATH=`pwd`/cmake-3.5.2-Linux-x86_64/bin/:$PATH
- make dependencies
- make
- npm install
before_script:
- mosquitto -d
script:
- npm test

