language: c
compiler: clang
sudo: true
dist: trusty
services:
- rabbitmq
node_js:
- '4'
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo add-apt-repository ppa:boost-latest/ppa -y
- sudo apt-get update -qq
- sudo apt-get install g++-4.8
- sudo apt-get install libboost1.55-all-dev libev-dev
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
- sudo apt-get install libcairo2-dev cmake libjpeg8-dev libpango1.0-dev libgif-dev
- sudo apt-get install libopencv-dev
install:
- export CC=gcc-4.8
- export CXX=g++-4.8
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd -
- mkdir -p build/
- curl -sSL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar -xzC ./build
- export PATH=`pwd`/cmake-3.5.2-Linux-x86_64/bin/:$PATH
- make dependencies
- make
- npm install
before_script:
- mosquitto -d
script:
- npm test

